import VNA_sweeps as sweeps

AVERAGES = 15
POWER = -25 #dB
EDELAY = 27.2 #ns
IFBAND = 1 #kHz
CENTERF = [7.30867] #GHz
SPAN = [20] #MHz
POINTS = [801]
OUTPUTFILE = "E06_1_VHPscan.csv"
TEMP = 13.6 #mK

#sweeps.getdata(CENTERF, SPAN, TEMP, AVERAGES, POWER, EDELAY, IFBAND, POINTS, OUTPUTFILE)
STARTPOWER = -25
ENDPOWER = -29
NUMSWEEPS = 5
count = 0
sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, CENTERF[0], SPAN[0], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[0], OUTPUTFILE)
#for i in CENTERF:
#    sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, i, SPAN[count], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[count], OUTPUTFILE)
#    count = count+1