import VNA_sweeps as sweeps

AVERAGES = 3000
POWER = -60 #dB
EDELAY = 27.32 #ns
IFBAND = 2 #kHz
CENTERF = 7.41025 #GHz
SPAN = 200 #MHz
POINTS = 301
OUTPUTFILE = "GaAs_Background.csv"
TEMP = 640 #mK

sweeps.getdata(CENTERF, SPAN, TEMP, AVERAGES, POWER, EDELAY, IFBAND, POINTS, OUTPUTFILE)
STARTPOWER = -10
ENDPOWER = -70
NUMSWEEPS = 7
count = 0
#sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, CENTERF[0], SPAN[0], TEMP, AVERAGES, EDELAY, IFBAND, POINTS, OUTPUTFILE)
#for i in CENTERF:
#    sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, i, SPAN[count], TEMP, AVERAGES, EDELAY, IFBAND, POINTS, OUTPUTFILE)
#    count = count+1