import VNA_sweeps as sweeps

AVERAGES = 2
POWER = -10 #dB
EDELAY = 27.2 #ns
IFBAND = 1 #kHz
CENTERF = [5.09011,6.38597,7.30867] #GHz
SPAN = [5,8,20] #MHz
POINTS = [501,501,801]
OUTPUTFILE = "E06_1_highpowerscan.csv"
TEMP = 13.6 #mK

#sweeps.getdata(CENTERF, SPAN, TEMP, AVERAGES, POWER, EDELAY, IFBAND, POINTS, OUTPUTFILE)
STARTPOWER = -10
ENDPOWER = -40
NUMSWEEPS = 4
count = 0
#sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, CENTERF[0], SPAN[0], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[0], OUTPUTFILE)
for i in CENTERF:
    sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, i, SPAN[count], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[count], OUTPUTFILE)
    count = count+1