import VNA_sweeps as sweeps

AVERAGES = 200
POWER = -50 #dB
EDELAY = 27.2 #ns
IFBAND = 1 #kHz
CENTERF = [5.09011,6.38597,7.30867] #GHz
SPAN = [5,8,20] #MHz
POINTS = [501,501,801]
OUTPUTFILE = "E06_1_power_scan.csv"
TEMP = 15 #mK

#sweeps.getdata(CENTERF, SPAN, TEMP, AVERAGES, POWER, EDELAY, IFBAND, POINTS, OUTPUTFILE)
STARTPOWER = -50
ENDPOWER = -90
NUMSWEEPS = 5
count = 0
#sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, CENTERF[0], SPAN[0], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[0], OUTPUTFILE)
for i in CENTERF:
    sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, i, SPAN[count], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[count], OUTPUTFILE)
    count = count+1