import VNA_sweeps as sweeps

AVERAGES = 200
POWER = -51 #dB
EDELAY = 27.2 #ns
IFBAND = 1 #kHz
CENTERF = [6.38597] #GHz
SPAN = [8] #MHz
POINTS = [501]
OUTPUTFILE = "E06_1_6p386GHz.csv"
TEMP = 13.9 #mK

#sweeps.getdata(CENTERF, SPAN, TEMP, AVERAGES, POWER, EDELAY, IFBAND, POINTS, OUTPUTFILE)
STARTPOWER = -53
ENDPOWER = -59
NUMSWEEPS = 4
count = 0
sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, CENTERF[0], SPAN[0], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[0], OUTPUTFILE)
#for i in CENTERF:
#    sweeps.powersweep(STARTPOWER, ENDPOWER, NUMSWEEPS, i, SPAN[count], TEMP, AVERAGES, EDELAY, IFBAND, POINTS[count], OUTPUTFILE)
#    count = count+1